### ISSUE TITLE
unable to read hotbits file - version 1.2.3

### ISSUE THREAD

**Issue by t0mmyz7** [isuretpolos/AetherOnePi#53]
Hi

I installed server, it is running, and I am running client. Soon as the client starts I see the erroe belowr in the terminal.

When I try to do analyze, I am also getting many of these errors.

while the GUI is showing hotbits 99, and the folder has all the hotbits. Also the files it is complaining about do exist inside the folder.

what am i doing wrong here ?

`22:25:39.204 [Thread-9] ERROR de.isuret.polos.AetherOnePi.processing2.hotbits.HotbitsHandler - unable to read hotbits file /home/pi/AetherOnePi/hotbits/hotbits_20210719_215948515.dat
com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x7b
 at [Source: (File); line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3549)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3294)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3520)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2902)
	at de.isuret.polos.AetherOnePi.processing2.hotbits.HotbitsHandler.loadHotbitsFromHarddisk(HotbitsHandler.java:123)
	at de.isuret.polos.AetherOnePi.processing2.hotbits.HotbitsHandler.access$100(HotbitsHandler.java:24)
	at de.isuret.polos.AetherOnePi.processing2.hotbits.HotbitsHandler$1.run(HotbitsHandler.java:63)
22:25:39.207 [Thread-9] ERROR de.isuret.polos.AetherOnePi.processing2.hotbits.HotbitsHandler - unable to read hotbits file /home/pi/AetherOnePi/hotbits/hotbits_20210719_215739598.dat
`

**Comment by t0mmyz7** [comment]
Linux raspberrypi 5.10.17-v7+ #1421 

pi@raspberrypi:~/AetherOnePi/hotbits $ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1+rpi1-b01)
OpenJDK Client VM (build 25.212-b01, mixed mode)

**Comment by t0mmyz7** [comment]
@isuretpolos  :)

**Comment by t0mmyz7** [comment]
ok so i found the issue here, I was using an older user manual and not latest, so I did not have instructions on Processing, and therefore HOTBITS were not created.

here is the latest user manual I used: https://radionics.home.blog/aetheonepi/

I had to install processing, create hotbits, and then error was gone.

closing this issue
