### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by t0mZ4** [isuretpolos/AetherOnePi#57]
hi

i get this error often while trying to use the software:
```

java.lang.NullPointerException
	at de.isuret.polos.AetherOnePi.processing2.elements.GuiElements.draw(GuiElements.java:403)
	at de.isuret.polos.AetherOnePi.processing2.AetherOneUI.draw(AetherOneUI.java:341)
	at processing.core.PApplet.handleDraw(PApplet.java:2426)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

```

for example,. if I start Grounding, after one run or two it freezes and produces this error

@isuretpolos

**Comment by isuretpolos** [comment]
Can you please provide a few more details, like which Java version, Operating System, etc?

**Comment by isuretpolos** [comment]
I close this bug, because it didn't appear anymore and no interest was shown by the issuer.
